apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nz6y1adb5-java-quarkus
  janus-idp.io/tekton: nz6y1adb5-java-quarkus
  backstage.io/kubernetes-id: nz6y1adb5-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nz6y1adb5-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
